[package]
org = "xlibb"
name = "mqtt"
version = "@toml.version@"
authors = ["xlibb"]
keywords = ["mqtt"]
repository = "https://github.com/xlibb/module-mqtt"
distribution = "2201.6.0"

[[platform.java11.dependency]]
groupId = "io.xlibb"
artifactId = "mqtt-native"
version = "@toml.version@"
path = "../native/build/libs/mqtt-native-@project.version@.jar"

# Azure dependencies
[[platform.java11.dependency]]
groupId = "org.eclipse.paho"
artifactId = "org.eclipse.paho.client.mqttv3"
version = "@paho.mqtt.version@"
path = "./lib/org.eclipse.paho.client.mqttv3-@paho.mqtt.version@.jar"
