[package]
org = "xlibb"
name = "mqtt"
version = "0.2.0"
authors = ["xlibb"]
keywords = ["mqtt"]
repository = "https://github.com/xlibb/module-mqtt"
distribution = "2201.6.0"

[[platform.java11.dependency]]
groupId = "io.xlibb"
artifactId = "mqtt-native"
version = "0.2.0"
path = "../native/build/libs/mqtt-native-0.2.0-SNAPSHOT.jar"

# Azure dependencies
[[platform.java11.dependency]]
groupId = "org.eclipse.paho"
artifactId = "org.eclipse.paho.mqttv5.client"
version = "1.2.5"
path = "./lib/org.eclipse.paho.mqttv5.client-1.2.5.jar"

[[platform.java11.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk15on"
version = "1.69"
path = "./lib/bcpkix-jdk15on-1.69.jar"
